import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  await prisma.medicine.createMany({
    data: [
      { name: "Paracetamol", brandName: "Panadol", ingredients: "Paracetamol 500 milligram", dosage: "500 milligram", indications: "Giảm đau, hạ sốt", contraindications: "Suy gan nặng", usageInstructions: "Uống 1 viên mỗi 4 đến 6 giờ, tối đa 4 gram một ngày", manufacturer: "GSK" },
      { name: "Ibuprofen", brandName: "Advil", ingredients: "Ibuprofen 200 milligram", dosage: "200 milligram", indications: "Giảm đau, kháng viêm", contraindications: "Loét dạ dày tá tràng", usageInstructions: "Uống 1 viên sau khi ăn", manufacturer: "Pfizer" },
      { name: "Amoxicillin", brandName: "Amoxil", ingredients: "Amoxicillin 500 milligram", dosage: "500 milligram", indications: "Nhiễm khuẩn", contraindications: "Dị ứng Penicillin", usageInstructions: "Uống 1 viên mỗi 8 giờ", manufacturer: "GSK" },
      { name: "Omeprazole", brandName: "Losec", ingredients: "Omeprazole 20 milligram", dosage: "20 milligram", indications: "Trào ngược dạ dày", contraindications: "Phối hợp với nelfinavir", usageInstructions: "Uống 1 viên trước bữa ăn 30 phút", manufacturer: "AstraZeneca" },
      { name: "Cetirizine", brandName: "Zyrtec", ingredients: "Cetirizine 10 milligram", dosage: "10 milligram", indications: "Viêm mũi dị ứng", contraindications: "Suy thận giai đoạn cuối", usageInstructions: "Uống 1 viên một ngày", manufacturer: "Johnson & Johnson" },
      { name: "Loratadine", brandName: "Clarityne", ingredients: "Loratadine 10 milligram", dosage: "10 milligram", indications: "Viêm mũi dị ứng", contraindications: "Mẫn cảm với thành phần thuốc", usageInstructions: "Uống 1 viên một ngày", manufacturer: "Bayer" },
      { name: "Metformin", brandName: "Glucophage", ingredients: "Metformin 500 milligram", dosage: "500 milligram", indications: "Đái tháo đường type 2", contraindications: "Suy thận nặng", usageInstructions: "Uống 1 viên cùng bữa ăn", manufacturer: "Merck" },
      { name: "Amlodipine", brandName: "Amlor", ingredients: "Amlodipine 5 milligram", dosage: "5 milligram", indications: "Tăng huyết áp", contraindications: "Sốc tim", usageInstructions: "Uống 1 viên một ngày", manufacturer: "Pfizer" },
      { name: "Losartan", brandName: "Cozaar", ingredients: "Losartan 50 milligram", dosage: "50 milligram", indications: "Tăng huyết áp", contraindications: "Phụ nữ có thai", usageInstructions: "Uống 1 viên một ngày", manufacturer: "Merck" },
      { name: "Loperamide", brandName: "Imodium", ingredients: "Loperamide 2 milligram", dosage: "2 milligram", indications: "Tiêu chảy cấp", contraindications: "Viêm loét đại tràng cấp", usageInstructions: "Uống 2 viên ban đầu, 1 viên sau mỗi lần tiêu chảy", manufacturer: "Johnson & Johnson" },
      { name: "Pantoprazole", brandName: "Protonix", ingredients: "Pantoprazole 40 milligram", dosage: "40 milligram", indications: "Trào ngược dạ dày", contraindications: "Mẫn cảm với dẫn xuất benzimidazole", usageInstructions: "Uống 1 viên trước bữa ăn sáng", manufacturer: "Pfizer" },
      { name: "Esomeprazole", brandName: "Nexium", ingredients: "Esomeprazole 40 milligram", dosage: "40 milligram", indications: "Loét dạ dày", contraindications: "Phối hợp với atazanavir", usageInstructions: "Uống 1 viên một ngày trước bữa ăn", manufacturer: "AstraZeneca" },
      { name: "Azithromycin", brandName: "Zithromax", ingredients: "Azithromycin 250 milligram", dosage: "250 milligram", indications: "Nhiễm khuẩn hô hấp", contraindications: "Tiền sử vàng da do azithromycin", usageInstructions: "Uống 2 viên ngày đầu, 1 viên các ngày sau", manufacturer: "Pfizer" },
      { name: "Cefuroxime", brandName: "Zinnat", ingredients: "Cefuroxime 500 milligram", dosage: "500 milligram", indications: "Nhiễm khuẩn", contraindications: "Dị ứng cephalosporin", usageInstructions: "Uống 1 viên mỗi 12 giờ", manufacturer: "GSK" },
      { name: "Cefixime", brandName: "Suprax", ingredients: "Cefixime 200 milligram", dosage: "200 milligram", indications: "Viêm phế quản", contraindications: "Dị ứng cephalosporin", usageInstructions: "Uống 1 viên mỗi 12 giờ", manufacturer: "Lupin" },
      { name: "Diclofenac", brandName: "Voltaren", ingredients: "Diclofenac 50 milligram", dosage: "50 milligram", indications: "Viêm khớp", contraindications: "Loét dạ dày tiến triển", usageInstructions: "Uống 1 viên sau khi ăn", manufacturer: "Novartis" },
      { name: "Meloxicam", brandName: "Mobic", ingredients: "Meloxicam 7.5 milligram", dosage: "7.5 milligram", indications: "Viêm khớp dạng thấp", contraindications: "Suy gan nặng", usageInstructions: "Uống 1 viên một ngày", manufacturer: "Boehringer Ingelheim" },
      { name: "Celecoxib", brandName: "Celebrex", ingredients: "Celecoxib 200 milligram", dosage: "200 milligram", indications: "Giảm đau xương khớp", contraindications: "Dị ứng sulfonamid", usageInstructions: "Uống 1 viên một ngày", manufacturer: "Pfizer" },
      { name: "Prednisolone", brandName: "Prelone", ingredients: "Prednisolone 5 milligram", dosage: "5 milligram", indications: "Kháng viêm", contraindications: "Nhiễm nấm toàn thân", usageInstructions: "Uống theo chỉ định bác sĩ", manufacturer: "Taro" },
      { name: "Methylprednisolone", brandName: "Medrol", ingredients: "Methylprednisolone 16 milligram", dosage: "16 milligram", indications: "Rối loạn dị ứng", contraindications: "Nhiễm khuẩn nặng", usageInstructions: "Uống theo chỉ định bác sĩ", manufacturer: "Pfizer" },
      { name: "Diphenhydramine", brandName: "Benadryl", ingredients: "Diphenhydramine 25 milligram", dosage: "25 milligram", indications: "Dị ứng", contraindications: "Trẻ sơ sinh", usageInstructions: "Uống 1 viên mỗi 4 đến 6 giờ", manufacturer: "Johnson & Johnson" },
      { name: "Fexofenadine", brandName: "Telfast", ingredients: "Fexofenadine 60 milligram", dosage: "60 milligram", indications: "Viêm mũi dị ứng", contraindications: "Trẻ em dưới 12 tuổi", usageInstructions: "Uống 1 viên hai lần một ngày", manufacturer: "Sanofi" },
      { name: "Montelukast", brandName: "Singulair", ingredients: "Montelukast 10 milligram", dosage: "10 milligram", indications: "Hen phế quản", contraindications: "Cơn hen cấp tính", usageInstructions: "Uống 1 viên vào buổi tối", manufacturer: "Merck" },
      { name: "Salbutamol", brandName: "Ventolin", ingredients: "Salbutamol 100 microgram", dosage: "100 microgram", indications: "Co thắt phế quản", contraindications: "Dọa sảy thai", usageInstructions: "Xịt 1 đến 2 nhát khi khó thở", manufacturer: "GSK" },
      { name: "Budesonide", brandName: "Pulmicort", ingredients: "Budesonide 200 microgram", dosage: "200 microgram", indications: "Hen phế quản", contraindications: "Dị ứng thành phần thuốc", usageInstructions: "Xịt dự phòng hàng ngày", manufacturer: "AstraZeneca" },
      { name: "Gliclazide", brandName: "Diamicron", ingredients: "Gliclazide 30 milligram", dosage: "30 milligram", indications: "Đái tháo đường type 2", contraindications: "Đái tháo đường type 1", usageInstructions: "Uống 1 viên vào bữa sáng", manufacturer: "Servier" },
      { name: "Glimepiride", brandName: "Amaryl", ingredients: "Glimepiride 2 milligram", dosage: "2 milligram", indications: "Đái tháo đường type 2", contraindications: "Nhiễm toan ceton", usageInstructions: "Uống 1 viên vào bữa sáng", manufacturer: "Sanofi" },
      { name: "Atorvastatin", brandName: "Lipitor", ingredients: "Atorvastatin 20 milligram", dosage: "20 milligram", indications: "Rối loạn mỡ máu", contraindications: "Bệnh gan tiến triển", usageInstructions: "Uống 1 viên một ngày", manufacturer: "Pfizer" },
      { name: "Rosuvastatin", brandName: "Crestor", ingredients: "Rosuvastatin 10 milligram", dosage: "10 milligram", indications: "Tăng cholesterol", contraindications: "Bệnh gan tiến triển", usageInstructions: "Uống 1 viên một ngày", manufacturer: "AstraZeneca" },
      { name: "Simvastatin", brandName: "Zocor", ingredients: "Simvastatin 20 milligram", dosage: "20 milligram", indications: "Giảm cholesterol", contraindications: "Phối hợp thuốc ức chế CYP3A4", usageInstructions: "Uống 1 viên vào buổi tối", manufacturer: "Merck" },
      { name: "Bisoprolol", brandName: "Concor", ingredients: "Bisoprolol 5 milligram", dosage: "5 milligram", indications: "Tăng huyết áp", contraindications: "Nhịp tim chậm dưới 60 lần một phút", usageInstructions: "Uống 1 viên một ngày", manufacturer: "Merck" },
      { name: "Metoprolol", brandName: "Betaloc", ingredients: "Metoprolol 50 milligram", dosage: "50 milligram", indications: "Đau thắt ngực", contraindications: "Sốc tim", usageInstructions: "Uống 1 viên một ngày", manufacturer: "AstraZeneca" },
      { name: "Valsartan", brandName: "Diovan", ingredients: "Valsartan 80 milligram", dosage: "80 milligram", indications: "Tăng huyết áp", contraindications: "Phụ nữ có thai", usageInstructions: "Uống 1 viên một ngày", manufacturer: "Novartis" },
      { name: "Enalapril", brandName: "Renitec", ingredients: "Enalapril 10 milligram", dosage: "10 milligram", indications: "Tăng huyết áp", contraindications: "Tiền sử phù mạch", usageInstructions: "Uống 1 viên một ngày", manufacturer: "Merck" },
      { name: "Captopril", brandName: "Capoten", ingredients: "Captopril 25 milligram", dosage: "25 milligram", indications: "Tăng huyết áp", contraindications: "Hẹp động mạch thận hai bên", usageInstructions: "Uống 1 viên hai lần một ngày", manufacturer: "BMS" },
      { name: "Aspirin", brandName: "Aspirin 81", ingredients: "Aspirin 81 milligram", dosage: "81 milligram", indications: "Dự phòng huyết khối", contraindications: "Rối loạn đông máu", usageInstructions: "Uống 1 viên một ngày", manufacturer: "Bayer" },
      { name: "Clopidogrel", brandName: "Plavix", ingredients: "Clopidogrel 75 milligram", dosage: "75 milligram", indications: "Phòng ngừa huyết khối động mạch", contraindications: "Chảy máu bệnh lý", usageInstructions: "Uống 1 viên một ngày", manufacturer: "Sanofi" },
      { name: "Domperidone", brandName: "Motilium", ingredients: "Domperidone 10 milligram", dosage: "10 milligram", indications: "Buồn nôn", contraindications: "Xuất huyết tiêu hóa", usageInstructions: "Uống 1 viên trước bữa ăn", manufacturer: "Johnson & Johnson" },
      { name: "Diosmectite", brandName: "Smecta", ingredients: "Diosmectite 3 gram", dosage: "3 gram", indications: "Tiêu chảy cấp", contraindications: "Quá mẫn với thành phần thuốc", usageInstructions: "Pha 1 gói với nước, uống giữa các bữa ăn", manufacturer: "Ipsen" },
      { name: "Oresol", brandName: "Oresol", ingredients: "Glucose, Natri, Kali", dosage: "1 gói", indications: "Bù nước và điện giải", contraindications: "Suy thận cấp", usageInstructions: "Pha 1 gói với 200 mililit nước", manufacturer: "WHO" },
      { name: "Vitamin C", brandName: "Laroscorbine", ingredients: "Ascorbic Acid 1000 milligram", dosage: "1000 milligram", indications: "Thiếu hụt Vitamin C", contraindications: "Sỏi thận", usageInstructions: "Uống 1 viên sủi một ngày", manufacturer: "Bayer" },
      { name: "Calcium Carbonate", brandName: "Calcium Corbiere", ingredients: "Calcium 500 milligram", dosage: "500 milligram", indications: "Bổ sung canxi", contraindications: "Tăng canxi máu", usageInstructions: "Uống 1 ống vào buổi sáng", manufacturer: "Sanofi" },
      { name: "Iron", brandName: "Tardyferon", ingredients: "Sắt sulfate 80 milligram", dosage: "80 milligram", indications: "Thiếu máu do thiếu sắt", contraindications: "Thừa sắt", usageInstructions: "Uống 1 viên trước bữa ăn", manufacturer: "Pierre Fabre" },
      { name: "Mebendazole", brandName: "Fugacar", ingredients: "Mebendazole 500 milligram", dosage: "500 milligram", indications: "Nhiễm giun sán", contraindications: "Phụ nữ có thai 3 tháng đầu", usageInstructions: "Uống 1 viên duy nhất", manufacturer: "Johnson & Johnson" },
      { name: "Albendazole", brandName: "Zentel", ingredients: "Albendazole 400 milligram", dosage: "400 milligram", indications: "Nhiễm ký sinh trùng", contraindications: "Phụ nữ có thai", usageInstructions: "Uống 1 viên duy nhất", manufacturer: "GSK" },
      { name: "Acyclovir", brandName: "Zovirax", ingredients: "Acyclovir 200 milligram", dosage: "200 milligram", indications: "Nhiễm virus Herpes", contraindications: "Dị ứng acyclovir", usageInstructions: "Uống 1 viên mỗi 4 giờ", manufacturer: "GSK" },
      { name: "Fluconazole", brandName: "Diflucan", ingredients: "Fluconazole 150 milligram", dosage: "150 milligram", indications: "Nhiễm nấm", contraindications: "Phối hợp với cisapride", usageInstructions: "Uống theo phác đồ", manufacturer: "Pfizer" },
      { name: "Mupirocin", brandName: "Bactroban", ingredients: "Mupirocin 2 phần trăm", dosage: "2 phần trăm", indications: "Nhiễm khuẩn ngoài da", contraindications: "Bôi diện rộng ở bệnh nhân suy thận", usageInstructions: "Bôi lên da 3 lần một ngày", manufacturer: "GSK" },
      { name: "Fusidic Acid", brandName: "Fucidin", ingredients: "Fusidic Acid 2 phần trăm", dosage: "2 phần trăm", indications: "Viêm da nhiễm khuẩn", contraindications: "Dị ứng thành phần thuốc", usageInstructions: "Bôi vùng tổn thương 2 đến 3 lần một ngày", manufacturer: "LEO Pharma" },
      { name: "Povidone Iodine", brandName: "Betadine", ingredients: "Povidone Iodine 10 phần trăm", dosage: "10 phần trăm", indications: "Sát khuẩn vết thương", contraindications: "Rối loạn tuyến giáp", usageInstructions: "Bôi trực tiếp lên vết thương", manufacturer: "Mundipharma" }
    ]
  })
}

main().catch((e) => {
  process.exit(1)
}).finally(async () => {
  await prisma.$disconnect()
})